In [1]:
import numpy as np

In [2]:
## Install numpy if not

#!pip install numpy

## How to create numpy array
            1) List
            2) in-build functions

#### Create 1-D Numpy array using 1-D list

In [3]:
# From list

my_list = [1,2,3,4,5]
type(my_list)

list

In [4]:
my_array = np.array(my_list)
type(my_array)

numpy.ndarray

In [5]:
my_list

[1, 2, 3, 4, 5]

In [6]:
my_array

array([1, 2, 3, 4, 5])

#### Create 2-D Numpy array using 2-D list

In [2]:
# 2D-List
two_list = [[2,3] , [4,5]]
two_list

[[2, 3], [4, 5]]

In [8]:
matrix = np.array(two_list)
matrix

array([[2, 3],
       [4, 5]])

In [9]:
matrix *matrix

array([[ 4,  9],
       [16, 25]])

In [10]:
## array stores homogeneuos element : same data type elements

ab1 = [1,2,3,'a','b']
ab1
print(ab1)

[1, 2, 3, 'a', 'b']


In [11]:
ab1_array = np.array(ab1)
print(ab1_array)

['1' '2' '3' 'a' 'b']


In [12]:
ab2 = [1 , 3.3, 5, 2]
np.array(ab2)

array([1. , 3.3, 5. , 2. ])

##### create Numpy Array using in-built Functions :
        1) arange
        2) zeros
        3) ones
        4) identity/eye-->to create identity matrix
        5) reshape

In [13]:
# in built functions 
np.arange(10) # by default the interval is 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(20 , 30 )

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [15]:
np.arange( 40 , 100 , 5)

array([40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros(5 , dtype = 'int')

array([0, 0, 0, 0, 0])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
array_5 = np.ones(5) * 10
array_5

array([10., 10., 10., 10., 10.])

In [20]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [21]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.identity(3)*3 # to generate identity matrix

array([[3., 0., 0.],
       [0., 3., 0.],
       [0., 0., 3.]])

In [23]:
np.eye(3)# to generate identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.random.randint(3, size = 10) # will randomly generate a single number between 0 to 3
# 0--> inclusive last number --> exclusive

array([1, 2, 2, 1, 1, 0, 2, 1, 1, 0])

In [25]:
np.random.randint(1, 20 , size = 5)# return 5 elements randomely between 1 to 20

array([ 4, 15,  9,  9, 11])

In [26]:
np.random.rand(3) # randomly generating number between 0 and 1

array([0.40128966, 0.19089405, 0.56351149])

In [27]:
np.random.randn(3 )

array([ 0.13501731, -0.07156367,  0.58605979])

In [28]:
np.random.randint(0 , 1 , 30)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.random.randn(5,5)

array([[-0.80924103, -1.22784894, -1.65154051, -0.89351812,  0.28553404],
       [-1.73332027, -0.65146964, -1.61811845,  0.4173321 ,  0.72207375],
       [ 0.04886996,  0.48967912, -0.31275813,  0.02545173, -0.12203222],
       [ 0.24662229,  0.15092015,  0.42581376,  0.20954494, -0.85037161],
       [-0.69221854, -0.84055512, -0.55848308,  1.549419  ,  1.97301778]])

In [30]:
## np.reshape
arr_1 = np.arange(20)
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
arr_1.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [32]:
arr_1.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [33]:
arr_1.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

## mathematical operations

In [34]:
arr_1 = np.array([5,1,7,2,3,4])

In [35]:
arr_1.max()

7

In [36]:
arr_1.min()

1

In [37]:
arr_1.argmax()# index of the max value

2

In [38]:
arr_1.argmin() # index of the min value in the array

1

In [39]:
arr_1

array([5, 1, 7, 2, 3, 4])

In [40]:
arr_1 + 2  

array([7, 3, 9, 4, 5, 6])

In [41]:
arr_1 - 4

array([ 1, -3,  3, -2, -1,  0])

In [42]:
arr_1 * 2

array([10,  2, 14,  4,  6,  8])

In [43]:
arr_1 / 2

array([2.5, 0.5, 3.5, 1. , 1.5, 2. ])

In [44]:
arr_2 = arr_1 * 2
print(arr_2)
arr_1

[10  2 14  4  6  8]


array([5, 1, 7, 2, 3, 4])

In [45]:
arr_1 * arr_2 

array([50,  2, 98,  8, 18, 32])

In [46]:
arr1=np.array([[1,2],[3,4],[5,0]])
arr2=np.array([[2,3],[4,5]])
print(arr1.shape)
print(arr2.shape)
np.matmul(arr1 , arr2
         )

(3, 2)
(2, 2)


array([[10, 13],
       [22, 29],
       [10, 15]])

##### Logical operations 

In [47]:
arr_1

array([5, 1, 7, 2, 3, 4])

In [48]:
arr_1<5

array([False,  True, False,  True,  True,  True])

In [49]:
arr_1[arr_1<5]

array([1, 2, 3, 4])

In [50]:
arr_1[arr_1 != 7]

array([5, 1, 2, 3, 4])

In [51]:
arr_1[arr_1 == 3]

array([3])

In [52]:
arr_1[arr_1 > 5]

array([7])

In [53]:
arr_1[(arr_1 > 5) | (arr_1==5)]

array([5, 7])

In [54]:
arr_1[(arr_1 != 5)  & (arr_1 <5)]

array([1, 2, 3, 4])

## indexing and slicing

In [55]:
arr_1

array([5, 1, 7, 2, 3, 4])

In [56]:
# access elemement 2
arr_1[3]

2

In [57]:
#access element 7
arr_1[2]

7

In [58]:
# access 1, 7, 2

arr_1[1:4]

array([1, 7, 2])

In [59]:
## Practice question
test_arr = np.array(['a' , 'b' ,'c' ,'d' ,'e' , 'f'])
test_arr

array(['a', 'b', 'c', 'd', 'e', 'f'], dtype='<U1')

 ##### Practice Questions:
        1) access element from b to e
        2) access element f only
        3)access element c and d
        4) access all elements except 'f'


In [60]:
test_arr[1:5]

array(['b', 'c', 'd', 'e'], dtype='<U1')

In [61]:
test_arr[5]

'f'

In [62]:
test_arr[2:4]

array(['c', 'd'], dtype='<U1')

In [63]:
test_arr[0:5]

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

##### Practice Questions:
    1) access element from b to e
    2) access element f only
    3)access element c and d
    4) access all elements except 'f

In [64]:
test_arr[-5:-1]

array(['b', 'c', 'd', 'e'], dtype='<U1')

In [65]:
test_arr[-1]

'f'

In [66]:
test_arr[-4:-2]

array(['c', 'd'], dtype='<U1')

In [67]:
test_arr[-6:-1]

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [68]:
## Array is mutuable: 

test_arr

array(['a', 'b', 'c', 'd', 'e', 'f'], dtype='<U1')

In [69]:
test_arr[2:4] =['A','B']
test_arr

array(['a', 'b', 'A', 'B', 'e', 'f'], dtype='<U1')

In [70]:
test_arr[-2: ] = '1'
test_arr

array(['a', 'b', 'A', 'B', '1', '1'], dtype='<U1')

In [72]:
arr_2d = np.array((
                        [5,10,15],
                        [20,25,30],
                        [35 , 40 , 45]
))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [73]:
## access element 40
arr_2d[2 , 1]


40

In [74]:
# access element 30
arr_2d[1, 2]

30

In [93]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

## practice questions:
        1) access 25 element
        2) access 35 value
        3) [10,15]
            [25,30]
        4) access [20,25,30]
        5) [5,10]
            [20,25]
        6) [20,25,30]
            [35,40,45]

In [92]:
arr_2d[-3:-1 , -3:-1]

array([[ 5, 10],
       [20, 25]])

In [94]:
arr_2d[-2:]

array([[20, 25, 30],
       [35, 40, 45]])

In [76]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [77]:
arr_2d[1,1]

25

In [78]:
arr_2d[2, 0]

35

In [80]:
arr_2d[0:2 ,1:3 ]

array([[10, 15],
       [25, 30]])

In [81]:
arr_2d[1]

array([20, 25, 30])

In [82]:
arr_2d[0:2, 0:2]

array([[ 5, 10],
       [20, 25]])

In [87]:
arr_2d[1:3 , 0:3]

array([[20, 25, 30],
       [35, 40, 45]])

In [90]:
arr_2d[-1 , 0:2]

array([35, 40])

## slice data based on random index of rows and columns

In [96]:
arr12 = np.array((
                    [5,10,15],
                    [20,25, 30],
                    [35, 40 , 45],
                    [1,2,3],
                    [40, 50 , 60]
    ))
arr12

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [ 1,  2,  3],
       [40, 50, 60]])

In [97]:
# [5,10,15]
# [1,2,3]

arr12[[0 , 3]]

array([[ 5, 10, 15],
       [ 1,  2,  3]])

In [98]:
arr12[ : , [0, 2]]

array([[ 5, 15],
       [20, 30],
       [35, 45],
       [ 1,  3],
       [40, 60]])

In [99]:
arr12

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [ 1,  2,  3],
       [40, 50, 60]])

In [100]:
# 10,25
# 30, 45
arr12[0:2 , 1]

array([10, 25])

In [103]:
# 20 and 60
arr12[[1,4] ,[0,2]]

array([20, 60])